### ISSUE TITLE
Does not work when using browserify build on node.js.

### ISSUE THREAD

**Issue by EvanCarroll** [kevinbeaty/any-promise#23] opened 2016-06-02 06:28 UTC
In an attempt to use this under browserify, i get

```text
/home/ecarroll/code/rl/bulk-load/dist/build.js:83                                                     
module.exports = require('./loader')(window, loadImplementation)                                      
                                     ^                                                                
                                                                                                      
ReferenceError: window is not defined                                                                 
    at Object.__dirname.2../loader (/home/ecarroll/code/rl/bulk-load/dist/build.js:83:38)             
    at s (/home/ecarroll/code/rl/bulk-load/dist/build.js:1:316)                                       
    at /home/ecarroll/code/rl/bulk-load/dist/build.js:1:367                                           
    at Object.__dirname.3.any-promise/register (/home/ecarroll/code/rl/bulk-load/dist/build.js:108:9) 
    at s (/home/ecarroll/code/rl/bulk-load/dist/build.js:1:316)                                       
    at e (/home/ecarroll/code/rl/bulk-load/dist/build.js:1:487)                                       
    at Object.<anonymous> (/home/ecarroll/code/rl/bulk-load/dist/build.js:1:505)                      
    at Module._compile (module.js:541:32)                                                             
    at Object.Module._extensions..js (module.js:550:10)                                               
    at Module.load (module.js:458:32)                                                                 
```

On Build.js:83, I see

```text
"use strict";                                                                
module.exports = require('./loader')(window, loadImplementation)             
                                                                             
/**                                                                          
 * Browser specific loadImplementation.  Always uses `window.Promise`        
 *                                                                           
 * To register a custom implementation, must register with `Promise` option. 
 */                                                                          
``` 

On Build.js:83, I see

```text
"use strict";                                                                
module.exports = require('./loader')(window, loadImplementation)             
                                                                             
/**                                                                          
 * Browser specific loadImplementation.  Always uses `window.Promise`        
 *                                                                           
 * To register a custom implementation, must register with `Promise` option. 
 */                                                                          
``` 

What's happening is that browserify is using the `browser` field in the [package.json](https://github.com/kevinbeaty/any-promise/blob/master/package.json). This references [register-shim.js](https://github.com/kevinbeaty/any-promise/blob/master/register-shim.js) which short circuits all of your clever logic. I'm not sure how to register the node-specific load implimentation I don't see it documented. this doesn't work `require('any-promise/register')('global.Promise');`

My suggestion is to remove the line in`package.conf` that specifies `browser:{}`. **In my case I'm using browserify to run some dependencies through babel for processing with node.**

**Comment by kevinbeaty** [comment] 2016-06-02 11:21
Hmm.. That's odd.  I have a make target to compile with browserify and it works just fine.  I wonder if it's something specific to your setup.  Do you have something I can look at to reproduce?

> What's happening is that browserify is using the browser field in the package.json.

This is intentional.  The "clever logic" is node specific and not intended for the browser.

> require('any-promise/register')('global.Promise');

This registration call will not work in the browser setting, as noted in the README.  You should use either the shortcut registration or "advanced registration" for using in browser.  

That said, 'global.Promise' and 'window.Promise' do not need to be registered as they are the defaults if that is what you want.

**Comment by kevinbeaty** [comment] 2016-06-02 11:27
>  In my case I'm using browserify to run some dependencies through babel for processing with node.

Oh. I missed this part. That's interesting. Honestly, I'm not sure how to address this use case right now because the `browserify` build is really intended for the `browser` here.  I'm not sure how to address your "browser build in node" use case without breaking the "browser build in browser".

**Comment by kevinbeaty** [comment] 2016-06-02 13:56
Can you try your setup with the changes from #24 to `register-shim.js` in your setup to see if it addresses your issue?  You should not have to register if 'global.Promise' is desired.

**Comment by EvanCarroll** [comment] 2016-06-02 15:46
Well, I did find a solution. Not a big fan of it because it really constrains `any-promise` to be built for the browser, or for node. It makes the solution one off. You can disable this resolution with `browser` using `browserField: false`, Here is my full compile for reference, I will try your patch now and get back to you.

```javascript
function compile(watch) {                     
  let bundler = browserify('./src/app.js', {  
      browserField: false,                    
      builtins: false,                        
      commondir: false,                       
      node:true,                              
      debug: true,                            
      insertGlobalVars: { process: undefined }
    }                                         
  ).transform(babelify.configure({            
    "presets": [                              
      "es2015",                               
      "stage-3"                               
    ],                                        
    "plugins": [                              
      "transform-runtime"                     
    ]                                         
  }));                                        
                                              
  if (watch) {                                
    bundler = watchify(bundler);              
    bundler.on('update', function() {         
      console.log('-> bundling...');          
      rebundle();                             
    });                                       
  }                                           
                                              
  bundle(bundler);                            
}                                             
```

**Comment by EvanCarroll** [comment] 2016-06-02 18:03
I'm of the mindset now that we're doing this the wrong way. What should be done is the `node:true` option permitted in the Browserify CLI (simplifying my above config substantially). And, this whole thing should be better documented on the Browserify project (not here). It's browserify that's reading `package.json`'s `browser` pragma and not providing an easy documented solution to that problem.

The patch you provided is also not ideal. It would work for me. ;) But, think of all the people using explicit registers to get it to work Bluebird? What of them? They'd still be SOL, and highly confused.

**Comment by kevinbeaty** [comment] 2016-06-02 18:34
> I'm of the mindset now that we're doing this the wrong way

Yeah, I was thinking about that too.  If you are really trying to use Node.js as a `browserify` compilation target, something like `node: true` would probably be the best thing to do.  We can work around it here (mostly) but you'll probably want that set for your other dependencies too.

> But, think of all the people using explicit registers to get it to work Bluebird? What of them? 

It would still work. Explicit registration takes precedence, the global Promise is the default.  The method we patched is only called if nothing was previously registered.

**Comment by kevinbeaty** [comment] 2016-06-02 18:38
The only things that would not work is the features only supported in Node.js, i.e: "basic registration" (`require('any-promise/register')('bluebird')`) and the attempt to auto-detect an implementation if none is registered. "Shortcuts" (`require('any-promise/register/bluebird')`) and advanced registration are better alternatives for the former and the latter only works in Node.js < 0.12 anyway.

**Comment by kevinbeaty** [comment] 2016-07-28 18:52
Closing as I think we've agreed no change is required.  Please reopen if I've misunderstood.

**Closed by kevinbeaty** 2016-07-28 18:52 UTC

**Comment by uniphil** [comment] 2017-01-19 03:51
Just to be super-clear for anyone else who stumbles upon this issue

**the magical [browserify CLI incantation](https://github.com/substack/node-browserify#usage) is:**

# `--node`

And then stuff just works! It should probably be in there regardless if you're browserifying for node!

(browserify + react + koa for an isomorphic app brought me here)
